// = vguimatsurface library

// ISurface
vtidx_DrawSetColor 10
vtidx_DrawFilledRect 12
vtidx_DrawOutlinedRect 14
vtidx_DrawLine 15
vtidx_DrawPolyLine 16
vtidx_DrawSetTextFont 17
vtidx_DrawSetTextColor 18
vtidx_DrawSetTextPos 20
vtidx_DrawPrintText 22
vtidx_GetScreenSize {
	default 37
	L4D2_2147 35
	TheLastStand 35
}
vtidx_CreateFont {
	default 64
	L4D2_2147 63
	TheLastStand 63
}
vtidx_SetFontGlyphSet {
	default 65
	L4D2_2147 64
	TheLastStand 64
}
vtidx_GetFontTall 67
vtidx_GetCharacterWidth 71
